server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transactions/**
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/auth/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true